# Generated by Django 4.2.3 on 2024-12-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oacademyapp", "0003_assignment_book_course_dictionary_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
