# Generated by Django 4.2.3 on 2024-12-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oacademyapp", "0005_alter_todo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
