# Generated by Django 4.2.3 on 2024-12-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oacademyapp", "0006_alter_todo_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
