# Generated by Django 4.2.3 on 2024-12-18 12:35

from datetime import datetime, timezone
from django.utils import timezone
from django.db import migrations, models

def forwards_func(apps, schema_editor):
    Todo = apps.get_model('oacademyapp', 'Todo')
    for todo in Todo.objects.all():
        if todo.due_date is None:  # If you need to set a default value
            todo.due_date = timezone.now()
            todo.save()

class Migration(migrations.Migration):

    dependencies = [
        ("oacademyapp", "0008_alter_todo_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
