# Generated by Django 4.2.3 on 2024-12-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oacademyapp", "0011_alter_todo_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="assignment",
        ),
    ]
