# Generated by Django 5.1.4 on 2024-12-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oacademyapp", "0012_remove_todo_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
