# Generated by Django 5.1.4 on 2024-12-24 14:38

import oacademyapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oacademyapp", "0013_alter_assignment_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="assignment",
        ),
        migrations.AddField(
            model_name="assignment",
            name="due_date",
            field=models.DateTimeField(default=oacademyapp.models.get_due_date),
        ),
    ]
